---
- name: Delete EC2 Instances
  hosts: localhost
  vars_files:
    - credentials.yml
    - vars.yml
  tasks:
    - name: Terminate every running instance in a region with the tag patu-ci-single-node-cluster.
      become: false
      ec2_instance:
        state: absent
        filters:
          "tag:NodeType": "patu-ci-single-node-cluster"
          instance-state-name: running
