name: Patu Periodic Cloud Performance and Scale Testing

on:
  push:
      branches:
        - main

jobs:
  deploy-perf-scale:
    name: deploy-perf-scale
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        cni: ["patu"]
        kube-distribution: ["kubeadm"]
    env:
      JOB_NAME: "patu-periodic-perfscale-${{ matrix.k8s-distro }}-${{ matrix.cni }}"
      CLOUD_PROVIDER: ${{ matrix.cni }}
      KUBE_DIST: ${{ matrix.k8s-distro }}
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Ansible and dependencies
      run: pip3.10 install boto boto3 ansible-vault ansible-core==2.13.3

    - name: Install amazon.aws Ansible library
      run: ansible-galaxy collection install amazon.aws

    - name: Create ansible ssh key
      run: |
        echo "${{ secrets.ANSIBLE_SSH_KEY }}" > patu-ci.pem
        chmod 0400 patu-ci.pem

    - name: Create vault password file
      run: |
        echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault-secret.txt
        chmod 0400 vault-secret.txt

    - name: Deploy EC2 Playbooks
      run: |
        ansible-playbook -vv deploy.yml --vault-password-file vault-secret.txt
        rm vault-secret.txt
        rm patu-ci

